### ISSUE TITLE
FileNotFoundError - sublime-status

### ISSUE THREAD

**Issue by jkbellew** [shagabutdinov/sublime-shell-status#2]
The dependency, StatusMessage, is installed without issue. But it appears that the installation of this was not complete. It's trying to find the file sublime-status and it's not in the path to be found. In fact the entire directory in Packages, ShellStatus, has not been created.

**Comment by shagabutdinov** [comment]
Did you install it from package control? I think it could be installed to "Installed Packages" folder instead of "Packages"; if it is, you can do following:
- Clone this repo to `Packages` folder under `SublimeShellStatus` name
- Or create `ShellStatus.sublime-settings` in your `Packages/User` folder with following contents: 

```
  {
    "command": "my-status-command" // path to custom command; you can copy and paste it from https://github.com/shagabutdinov/sublime-shell-status/blob/master/sublime-status
  }
```
- Or open project settings (`Menu -> Project -> Edit project`) and insert following (this will work on per-project basis): 

```
  {
    ...,
    "settings": {
      "status_command": "my-status-command", // path to custom command
      ...
    }
  }
```

**Comment by shagabutdinov** [comment]
I close it as outdated. Please, reopen if issue still remains.
